apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prunetestapp
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocdprunedemo  
    server: 'https://kubernetes.default.svc'
  source:
    path: AswathyAsokan/demo-nginx
    repoURL: 'https://github.com/OpsMx/argo-training.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true