apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-onesource
  namespace: argocd
spec:
  destination:
    namespace: argocd-j
    server: 'https://kubernetes.default.svc'
  source:
    path: Jeevan/values/v-git/v-gitone
    repoURL: 'https://github.com/OpsMx/argo-training.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
