apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-training-1
spec:
  destination:
    name: ''
    namespace: argo-training
    server: 'https://kubernetes.default.svc'
  source:
    path: Tanmay/Test
    repoURL: 'https://github.com/OpsMx/argo-training.git'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
