apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-repo-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-namespace
  sources:  # Use 'sources' array for multiple repositories
    - repoURL: https://github.com/deepakjatoth12/argo-app.git
      path: raj-app
      targetRevision: HEAD
    - repoURL: https://github.com/OpsMx/argo-training.git
      path: Rajesh/apps
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
