apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-sources
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: my-task
  sources:
    - repoURL: https://github.com/OpsMx/argo-training.git
      path: Rajesh/data/firstsource
      targetRevision: HEAD
    - repoURL: https://github.com/OpsMx/argo-training/tree/main/Rajesh.git
      path: Rajesh/data/secondsource
      targetRevision: HEAD
