apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-appset
spec:
  generators:
    - list:
        elements:
          - name: guestbook-ui
            repoURL: https://github.com/OpsMx/argo-training.git          #pod
            targetRevision: HEAD
            path: Rajesh/test
          - name: nginx-deployment12
            repoURL: https://github.com/OpsMx/argo-training.git           #service
            targetRevision: HEAD
            path: Rajesh/test3
  template:
    metadata:
      name: "{{ .name }}-app"
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
