apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-onesource
  namespace: argocd
spec:
  destination:
    namespace: argocd-j
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/OpsMx/argo-training.git'
    path: Jeevan/values/v-helm/v-helmone.yaml
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
