apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: ApplicationSet
  namespace: argocd
spec:
  generator:
  - list:
      elements:
      - namespace: dev
      - namespace: test
      - namespace: uat
  template: 
    metadata:
      name: '{{namespace}}'
    spec: 
      project: default
      source: 
        repoURL: https://github.com/OpsMx/argo-training.git
        targetRevision: 'HEAD'
        path: Rajesh/test
      destination:
        server: https://kubernetes.default.svc
      namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
     
	
