apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: color-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - namespace: dev
          - namespace: test
          - namespace: uat
  template:
    metadata:
      name: '{{namespace}}-color-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/your-repo/color-app.git'  # Replace with your actual repo URL
        targetRevision: 'main'  # Replace with your desired branch or commit hash
        path: 'color-app'  # The path within the repo where the app's manifest is located
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'  # This will be dynamically substituted for each namespace in the generator
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
