apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-twodiffsource
  namespace: argocd
spec:
  destination:
    namespace: argocd-j
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/bitthalpatidar/test-argo.git'
      path: datas/helm/single-helm
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
    - repoURL: 'https://github.com/OpsMx/argo-training.git'
      path: Jeevan/values/v-helm/v-helmtwo/v-helmtwodiff
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
