apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: initalapp
  namespace: argocd
spec:
  destination:
    namespace: newnamespace
    server: 'https://kubernetes.default.svc'
  source:
    path: NagendraOpsmx/test/
    repoURL: 'https://github.com/OpsMx/argo-training.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true