apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-twosource
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-j
  sources:
    - repoURL: https://github.com/OpsMx/argo-training.git
      path: Jeevan/values/v-git/v-gittwo/v-g1.yaml
      targetRevision: HEAD
    - repoURL: https://github.com/OpsMx/argo-training.git
      path: Jeevan/values/v-git/v-gittwo/v-g2.yaml
      targetRevision: HEAD
